<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6d98e2d44080d5cb4bc2e028430ccae1
{
    public static $prefixLengthsPsr4 = array (
        'v' => 
        array (
            'vendor\\wplms-child\\' => 19,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'vendor\\wplms-child\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'FPDF' => __DIR__ . '/..' . '/setasign/fpdf/fpdf.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6d98e2d44080d5cb4bc2e028430ccae1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6d98e2d44080d5cb4bc2e028430ccae1::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit6d98e2d44080d5cb4bc2e028430ccae1::$classMap;

        }, null, ClassLoader::class);
    }
}
